version: '3.9'

services:
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=feastival
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
